import streamlit as st
import pandas as pd
import re
from datetime import datetime
from afexcloud.layout import bootstrap_page

# 1. Page Config
st.set_page_config(page_title="DNA Processor | AfexCloud", page_icon="🌉", layout="wide")

# 2. Bootstrap Style
bootstrap_page()

# 3. Tool Logic
st.title("🌉 DNA Processor (The Bridge)")
st.info("Upload the CSV generated by your local Git Bash script to integrate the DNA into your AfexCloud project.")

# --- FILE UPLOADER ---
uploaded_file = st.file_uploader("📤 Upload Local Bash Results (CSV)", type="csv")

if uploaded_file:
    try:
        # Load the local results
        df = pd.read_csv(uploaded_file)
        
        # Validation: Check if it looks like your Bash output
        required_cols = ['Name', 'Artist', 'Key', 'BPM']
        if not all(col in df.columns for col in required_cols):
            st.error(f"Missing Columns. Ensure your CSV has: {', '.join(required_cols)}")
        else:
            st.success(f"Successfully imported {len(df)} tracks from local analysis.")
            
            # --- THE INTERACTIVE "TABLE OF SORTS" ---
            st.subheader("📊 Integrated Master Log")
            st.caption("Tip: You can now sort by BPM or Key, and copy segments (Ctrl+C) for your DJ logs.")
            
            # Allow the larks to sort and interact with the local data in the cloud
            edited_df = st.data_editor(
                df,
                hide_index=True,
                use_container_width=True,
                num_rows="dynamic"
            )
            
            # --- MASTER PROJECT DOWNLOAD ---
            st.write("---")
            col1, col2 = st.columns(2)
            
            with col1:
                # Standardize filename based on the Global Project name
                safe_proj = st.session_state.get("_safe_proj", "Project")
                stamp = datetime.now().strftime("%Y%m%d")
                out_name = f"{safe_proj}_Master_DJ_Log_{stamp}.csv"
                
                st.download_button(
                    "📥 Download Master DJ Log",
                    edited_df.to_csv(index=False).encode('utf-8'),
                    out_name,
                    "text/csv",
                    help="Save the final, cleaned version to your project folder."
                )
            
            with col2:
                # Option to move straight to Batching
                if st.button("📦 Ready to Create Batches?"):
                    st.toast("Switch to the 'Batch Manager' page and upload this Master Log!")

    except Exception as e:
        st.error(f"Failed to process the CSV: {e}")

else:
    st.markdown("""
    ### 🛠️ Pro-Level Workflow:
    1. Run your `playlist_analyzer.py` in **Git Bash** on your local machine.
    2. Save the results as a **CSV**.
    3. Upload that file here to use the **AfexCloud** interactive tools.
    """)
